# Generated by Django 5.2.1 on 2025-06-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='tables',
        ),
        migrations.AddField(
            model_name='employee',
            name='tables',
            field=models.ManyToManyField(related_name='employees', to='app.table'),
        ),
    ]
