# Generated by Django 5.2.1 on 2025-06-04 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_employee_tables_employee_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='tables',
        ),
        migrations.AddField(
            model_name='table',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='app.employee'),
        ),
    ]
