# Generated by Django 5.2.1 on 2025-06-04 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_employee_tables_table_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='app.employee'),
        ),
    ]
