# Generated by Django 5.2.1 on 2025-06-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_table_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
