# Generated by Django 5.2.1 on 2025-06-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_ordering_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='ordered_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
