# Generated by Django 5.2.1 on 2025-06-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ordering_ordered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='ordered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
