# Generated by Django 5.2.1 on 2025-06-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_ordering_ordered_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedfood',
            name='food',
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_foods', to='app.food'),
        ),
    ]
