# Generated by Django 5.2.1 on 2025-06-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_orderedfood_food_orderedfood_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
