# Generated by Django 5.2.1 on 2025-06-08 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_orderedfood_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedfood',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_foods', to='app.food'),
        ),
    ]
