# Generated by Django 5.2.1 on 2025-06-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_orderedfood_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('done', 'done'), ('delivered', 'delivered')], default='in_progress', max_length=50),
        ),
    ]
