# Generated by Django 5.2.1 on 2025-06-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_ordering_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='time_to_prepare',
            field=models.IntegerField(default=-5),
        ),
    ]
