# Generated by Django 5.2.1 on 2025-06-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_food_time_to_prepare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='time_to_prepare',
            field=models.CharField(default=-5),
        ),
    ]
