# Generated by Django 5.2.1 on 2025-06-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_food_time_to_prepare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='time_to_prepare',
            field=models.CharField(default='10-15', help_text='in minutes'),
        ),
    ]
