# Generated by Django 5.2.1 on 2025-06-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_food_time_to_prepare'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_number',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
