# Generated by Django 5.2.1 on 2025-07-19 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_food_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('ordered_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('IN_PROGERESS', 'IN_PROGERESS'), ('DONE', 'DONE'), ('DELIVERED', 'DELIVERED')], default='in_progress', max_length=50)),
            ],
            options={
                'verbose_name': 'Orders',
            },
        ),
        migrations.RemoveField(
            model_name='table',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='table_number',
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_foods', to='app.orders'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='Ordering',
        ),
    ]
