# Generated by Django 5.2.1 on 2025-07-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Courier', 'Courier'), ('Client', 'Client'), ('Admin', 'Admin')], default='Client'),
        ),
    ]
